# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/mainConversionDataBase.ui'
#
# Created: Mon Jul 11 21:03:53 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_conversionDataBase(object):
    def setupUi(self, conversionDataBase):
        conversionDataBase.setObjectName(_fromUtf8("conversionDataBase"))
        conversionDataBase.resize(570, 630)
        self.gridLayout = QtGui.QGridLayout(conversionDataBase)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(conversionDataBase)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.tabWidget = QtGui.QTabWidget(self.frame)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 531, 561))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 491, 251))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.combo_Banco1 = QtGui.QComboBox(self.groupBox)
        self.combo_Banco1.setGeometry(QtCore.QRect(10, 40, 391, 22))
        self.combo_Banco1.setObjectName(_fromUtf8("combo_Banco1"))
        self.bt_campos1 = QtGui.QPushButton(self.groupBox)
        self.bt_campos1.setGeometry(QtCore.QRect(410, 40, 61, 23))
        self.bt_campos1.setObjectName(_fromUtf8("bt_campos1"))
        self.tv_Banco1 = QtGui.QTreeView(self.groupBox)
        self.tv_Banco1.setGeometry(QtCore.QRect(10, 70, 471, 171))
        self.tv_Banco1.setObjectName(_fromUtf8("tv_Banco1"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 280, 491, 241))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.combo_Banco2 = QtGui.QComboBox(self.groupBox_2)
        self.combo_Banco2.setGeometry(QtCore.QRect(10, 40, 391, 22))
        self.combo_Banco2.setObjectName(_fromUtf8("combo_Banco2"))
        self.bt_campos2 = QtGui.QPushButton(self.groupBox_2)
        self.bt_campos2.setGeometry(QtCore.QRect(410, 40, 61, 23))
        self.bt_campos2.setObjectName(_fromUtf8("bt_campos2"))
        self.tv_Banco2 = QtGui.QTreeView(self.groupBox_2)
        self.tv_Banco2.setGeometry(QtCore.QRect(10, 70, 471, 161))
        self.tv_Banco2.setObjectName(_fromUtf8("tv_Banco2"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 280, 501, 241))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 46, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.ed_host2 = QtGui.QLineEdit(self.groupBox_3)
        self.ed_host2.setGeometry(QtCore.QRect(80, 30, 401, 20))
        self.ed_host2.setObjectName(_fromUtf8("ed_host2"))
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(10, 70, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.ed_database2 = QtGui.QLineEdit(self.groupBox_3)
        self.ed_database2.setGeometry(QtCore.QRect(80, 70, 401, 20))
        self.ed_database2.setObjectName(_fromUtf8("ed_database2"))
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(10, 110, 46, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.ed_userP2 = QtGui.QLineEdit(self.groupBox_3)
        self.ed_userP2.setGeometry(QtCore.QRect(80, 110, 401, 20))
        self.ed_userP2.setObjectName(_fromUtf8("ed_userP2"))
        self.ed_passwordP2 = QtGui.QLineEdit(self.groupBox_3)
        self.ed_passwordP2.setGeometry(QtCore.QRect(80, 150, 401, 20))
        self.ed_passwordP2.setObjectName(_fromUtf8("ed_passwordP2"))
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(10, 150, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.testconect_Postgres2 = QtGui.QPushButton(self.groupBox_3)
        self.testconect_Postgres2.setGeometry(QtCore.QRect(360, 200, 120, 23))
        self.testconect_Postgres2.setObjectName(_fromUtf8("testconect_Postgres2"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 501, 251))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.ed_host = QtGui.QLineEdit(self.groupBox_4)
        self.ed_host.setGeometry(QtCore.QRect(80, 30, 401, 20))
        self.ed_host.setObjectName(_fromUtf8("ed_host"))
        self.label_9 = QtGui.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(10, 70, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.ed_database = QtGui.QLineEdit(self.groupBox_4)
        self.ed_database.setGeometry(QtCore.QRect(80, 70, 401, 20))
        self.ed_database.setObjectName(_fromUtf8("ed_database"))
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(10, 110, 46, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.ed_userP = QtGui.QLineEdit(self.groupBox_4)
        self.ed_userP.setGeometry(QtCore.QRect(80, 110, 401, 20))
        self.ed_userP.setObjectName(_fromUtf8("ed_userP"))
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(10, 150, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.ed_passwordP = QtGui.QLineEdit(self.groupBox_4)
        self.ed_passwordP.setGeometry(QtCore.QRect(80, 150, 401, 20))
        self.ed_passwordP.setObjectName(_fromUtf8("ed_passwordP"))
        self.label_12 = QtGui.QLabel(self.groupBox_4)
        self.label_12.setGeometry(QtCore.QRect(10, 30, 46, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.testconect_Postgres = QtGui.QPushButton(self.groupBox_4)
        self.testconect_Postgres.setGeometry(QtCore.QRect(360, 210, 120, 23))
        self.testconect_Postgres.setObjectName(_fromUtf8("testconect_Postgres"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 2)
        self.bt_ok = QtGui.QPushButton(conversionDataBase)
        self.bt_ok.setObjectName(_fromUtf8("bt_ok"))
        self.gridLayout.addWidget(self.bt_ok, 1, 0, 1, 1)
        self.bt_fechar = QtGui.QPushButton(conversionDataBase)
        self.bt_fechar.setObjectName(_fromUtf8("bt_fechar"))
        self.gridLayout.addWidget(self.bt_fechar, 1, 1, 1, 1)

        self.retranslateUi(conversionDataBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(conversionDataBase)

    def retranslateUi(self, conversionDataBase):
        conversionDataBase.setWindowTitle(QtGui.QApplication.translate("conversionDataBase", "Conversion DataBase", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("conversionDataBase", "Banco de Dados (Extraindo Dados)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("conversionDataBase", "Tabela", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_campos1.setText(QtGui.QApplication.translate("conversionDataBase", "Campos", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("conversionDataBase", "Banco de Dados (Inserido Dados)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("conversionDataBase", "Tabela", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_campos2.setText(QtGui.QApplication.translate("conversionDataBase", "Campos", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("conversionDataBase", "Conversão de Dados", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("conversionDataBase", "Banco de Dados (Inserindo Dados)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("conversionDataBase", "Host:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("conversionDataBase", "Data Base:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("conversionDataBase", "User:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("conversionDataBase", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.testconect_Postgres2.setText(QtGui.QApplication.translate("conversionDataBase", "Teste Conexão", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("conversionDataBase", "Banco de Dados (Extraindo Dados)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("conversionDataBase", "Data Base:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("conversionDataBase", "User:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("conversionDataBase", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("conversionDataBase", "Host:", None, QtGui.QApplication.UnicodeUTF8))
        self.testconect_Postgres.setText(QtGui.QApplication.translate("conversionDataBase", "Teste Conexão", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("conversionDataBase", "Configurar Conexão", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_ok.setText(QtGui.QApplication.translate("conversionDataBase", "&OK", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_fechar.setText(QtGui.QApplication.translate("conversionDataBase", "&Fechar", None, QtGui.QApplication.UnicodeUTF8))

